<h1>Inscription</h1>
<?php if($this->inscription>0){
    ?>
    <div class="alert alert-success"><strong>Félicitations !</strong> Vous vous êtes inscrit</div>
    <?php
}elseif ($this->inscription===false){
    ?>
    <div class="alert alert-danger"><strong>ERREUR !</strong> Vous n'avez pas pu être inscrit</div>
    <?php
}
?>
<form enctype="multipart/form-data" action="inscription" method="POST">
    <div class="form-group">
        <label for="login">Login:</label>
        <input type="text" class="form-control" name="login" id="login">
    </div>
    <div class="form-group">
        <input type="hidden" name="MAX_FILE_SIZE" value="200000" />
        <label for="image">Avatar : </label><input type="file" name="image" id="image" />

    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email">
    </div>
    <div class="form-group">
        <label for="pwd">Mot de passe:</label>
        <input name="password" type="password" class="form-control" id="pwd">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>