<h1>Login</h1>
<?php if($this->login==1){
    ?>
    <div class="alert alert-success"><strong>Félicitations !</strong> Vous vous êtes loggé</div>
    <?php
}elseif ($this->login===false){
    ?>
    <div class="alert alert-danger"><strong>ERREUR !</strong> Vous n'avez pas pu être loggé</div>
    <?php
}
?>
<form action="login" method="POST">
    <div class="form-group">
        <label for="login">Login:</label>
        <input type="text" class="form-control" name="login" id="login">
    </div>
    <div class="form-group">
        <label for="pwd">Mot de passe:</label>
        <input name="password" type="password" class="form-control" id="pwd">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>