

<h1>VENEZ ACHETER DES FILMS SUR MA PLATFORME</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">

            <?php foreach($this->films as $key => $film){
                if( $key == 0 )
                    $class= 'active';
                else
                    $class = ''; ?>
                <div class="carousel-item <?php echo $class;?>">
                    <img class="d-block w-100" src="images/film/<?php echo $film->image;?>">
                </div>
                <?php

            }  ?>



    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>