<!DOCTYPE><html>
<head>
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo WEB_ROOT; ?>/stylesheets/custom.css">


</head>
<body>
<div class="container">
    <?php include('menu.phtml');?>
    <?php

    if( isset( $_SESSION['message']['success'] ) && count($_SESSION['message']['success'])>0) {
        foreach ($_SESSION['message']['success'] as $mess) {
        ?>
        <div class="alert alert-success"><strong>Félicitations !</strong>
            <?php echo $mess; ?>
        </div>
        <?php
        }
    }
    if( isset($_SESSION['message']['fail']) && count($_SESSION['message']['fail'])>0) {
        foreach($_SESSION['message']['fail'] as $mess){
        ?>
        <div class="alert alert-danger"><strong>Erreur !</strong>
            <?php echo $mess;?>
        </div>
        <?php
            }
    }
    unset($_SESSION['message']); ?>
    <?php echo $this->content(); ?>
</div>
</body>
</html>