<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Vente de DVD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Accueil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/films">Films<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/categories">Catégories</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/add/categorie">Ajouter une catégorie</a>
                    <a class="dropdown-item" href="/add/film">Ajouter un film</a>

                </div>
            </li>
            <?php
            if($_SESSION['user']){
            ?><li class="nav-item"><a class="nav-link float-left menu-panier" href="<?php echo WEB_ROOT; ?>/panier">Panier</a> <?php
                    if( isset($_SESSION['user']['panier']) && count($_SESSION['user']['panier'])>0){
                        $total = 0;
                        foreach($_SESSION['user']['panier'] as $panier){
                            $total+=$panier['quantite'];
                        }
                        echo '<i class="float-left fas fa-certificate"></i>
                           <span class="nbPanier">'.$total.'</span>
                    ';
                    }
                } ?></li>
        </ul>
        <?php if(!isset($_SESSION['user'])){ ?>
                <a class="mr-sm-2" href="<?php echo WEB_ROOT; ?>/inscription">Inscription</a></li>
                <a class="mr-sm-2" href="<?php echo WEB_ROOT; ?>/login">Connexion</a></li>
                <?php } else{
                    ?>
                <a class="mr-sm-2" href="<?php echo WEB_ROOT; ?>/deconnexion">Déconnexion</a>
                <?php } ?>

    </div>
</nav>